using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

namespace ModFramework.UI.Custom
{
    /// <summary>
    /// Singleton overlay for displaying styled tooltips.
    /// </summary>
    public class ModTooltip : MonoBehaviour
    {
        private static ModTooltip _instance;
        private RectTransform _rect;
        private Text _text;
        private CanvasGroup _group;

        public static void Show(string content)
        {
            if (_instance == null) CreateInstance();
            _instance._text.text = content;
            _instance._group.alpha = 1f;
            _instance.UpdatePosition();
        }

        public static void Hide()
        {
            if (_instance != null)
                _instance._group.alpha = 0f;
        }

        private static void CreateInstance()
        {
            GameTheme.Initialize();
            GameObject tooltipObj = new GameObject("ModTooltip_Singleton");
            tooltipObj.transform.SetParent(WindowManager.Instance.Canvas.transform, false);
            tooltipObj.transform.SetAsLastSibling();

            _instance = tooltipObj.AddComponent<ModTooltip>();
            _instance._rect = tooltipObj.AddComponent<RectTransform>();
            _instance._rect.pivot = new Vector2(0f, 1f); // Top Left anchor
            
            // Background
            Image bg = tooltipObj.AddComponent<Image>();
            bg.color = new Color(0.1f, 0.1f, 0.1f, 0.95f); // Dark nearly opaque background
            if (GameTheme.WindowSprite != null)
            {
                bg.sprite = GameTheme.WindowSprite;
                bg.type = Image.Type.Sliced;
            }

            // Auto-resize
            ContentSizeFitter csf = tooltipObj.AddComponent<ContentSizeFitter>();
            csf.horizontalFit = ContentSizeFitter.FitMode.PreferredSize;
            csf.verticalFit = ContentSizeFitter.FitMode.PreferredSize;

            HorizontalLayoutGroup hlg = tooltipObj.AddComponent<HorizontalLayoutGroup>();
            hlg.padding = new RectOffset(6, 6, 4, 4);

            // Text
            GameObject textObj = new GameObject("Text");
            textObj.transform.SetParent(tooltipObj.transform, false);
            _instance._text = textObj.AddComponent<Text>();
            _instance._text.font = GameTheme.GameFont;
            _instance._text.fontSize = GameTheme.DefaultFontSize - 2; // slightly smaller font for tooltips
            _instance._text.color = Color.white;
            _instance._text.alignment = TextAnchor.MiddleLeft;

            _instance._group = tooltipObj.AddComponent<CanvasGroup>();
            _instance._group.blocksRaycasts = false;
            _instance._group.interactable = false;
            _instance._group.alpha = 0f;
        }

        private void Update()
        {
            if (_group.alpha > 0)
            {
                UpdatePosition();
                // Ensure we are always on top of EVERYTHING
                transform.SetAsLastSibling();
            }
        }

        private void UpdatePosition()
        {
            Vector2 mousePos = Input.mousePosition;
            _rect.position = new Vector3(mousePos.x + 10f, mousePos.y - 10f, 0f);
            
            // Clamp to screen bounds logic if necessary
            // In a high res game it's usually fine initially, but good to add if polishing later
        }
    }

    /// <summary>
    /// Component placed on UI elements to trigger standard ModTooltips on hover.
    /// </summary>
    public class ModTooltipTrigger : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler
    {
        public string Text;
        
        public void OnPointerEnter(PointerEventData eventData)
        {
            if (!string.IsNullOrEmpty(Text)) ModTooltip.Show(Text);
        }

        public void OnPointerExit(PointerEventData eventData)
        {
            ModTooltip.Hide();
        }
    }

    public static class TooltipExtensions
    {
        /// <summary>
        /// Super easy extension method to add a tooltip to ANY UI element generated by the framework.
        /// e.g. ModButton.Create(...).AddTooltip("Click to confirm");
        /// </summary>
        public static GameObject AddTooltip(this GameObject obj, string text)
        {
            ModTooltipTrigger trigger = obj.GetComponent<ModTooltipTrigger>();
            if (trigger == null) trigger = obj.AddComponent<ModTooltipTrigger>();
            trigger.Text = text;
            return obj;
        }
    }
}
